apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: net-remote
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/rmedina97/peering-guide.git'
    targetRevision: HEAD
    path: net-remote
  destination:
    server: 'https://172.16.183.16:6443'  # URL API del cluster remoto (come registrato in argocd cluster add)

