apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: off-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/rmedina97/peering-guide.git'
    targetRevision: HEAD
    path: offloading-local
  destination:
    server: 'https://kubernetes.default.svc'   # cluster locale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true