apiVersion: v1
kind: Secret
metadata:
  labels:
    liqo.io/remote-cluster-id: provider
    networking.liqo.io/gateway-resource: "true"
  name: gw-keys
  namespace: liqo-tenant-provider
type: Opaque
data:
  privateKey: eO1CP6S5bCtFj0iExDDFyDuGzAk+/+BitFDkZ43gc30=
  publicKey: ahPstVhybRiIyxSPhZgfWkc5vMUaJTFHaCcTr2KEW2A=