apiVersion: networking.liqo.io/v1beta1
kind: PublicKey
metadata:
  labels:
    liqo.io/remote-cluster-id: provider
    networking.liqo.io/gateway-resource: "true"
  name: gw-publickey
  namespace: liqo-tenant-provider
spec:
  publicKey: SU+Ba3jBNgofBrZtVHwad1VJotcVs4TmgpOdFQhx/UE=