apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: # Mandatory labels for Liqo
    liqo.io/remote-cluster-id: consumer
  name: liqo-binding-liqo-remote-controlplane
  namespace: liqo-tenant-consumer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-remote-controlplane
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: myuser