apiVersion: authentication.liqo.io/v1beta1
kind: Tenant
metadata:
  labels: # Mandatory labels for Liqo
    liqo.io/remote-cluster-id: consumer
  name: my-tenant
  namespace: liqo-tenant-consumer
spec:
  clusterID: consumer # The cluster ID of the remote cluster
  authzPolicy: TolerateNoHandshake
  tenantCondition: Active